### ISSUE TITLE
Add Gitter channel to project

### ISSUE THREAD

**Issue by LexiconCode** [Danesprite/dragonfly#1]
Greetings, first off I want to thank you for pursuing adding CMU Pocket Sphinx as a backend for dragonfly. It has been a long hope to see alternative speech recognition engines especially open source projects integrated into dragonfly. 

I found gitter as excellent tool to help the exchange of ideas and community. Typically ideas might be formed in gitter chat and when formalized opened up as an github issue or pull request. Depends on your Preference but I thought I might suggest it is a way of fostering community around Pocket Sphinx.
https://gitter.im/

**Comment by Danesprite** [comment]
Hey thanks! I think the main thing left to do at the moment is full action support on non-Windows systems.
I was thinking of some way to foster a community around this and it sounds like gitter would be good. I might also post on the [dragonfly Google group](https://groups.google.com/forum/#!forum/dragonflyspeech) about it.

**Comment by Danesprite** [comment]
I've made a gitter: [sphinx-dragonfly](https://gitter.im/sphinx-dragonfly/).
