### ISSUE TITLE
Clipboard multiplatform overhaul

### ISSUE THREAD

**Issue by gerrish** [Danesprite/dragonfly#15]
I had some problems with the dragonfly clipboard implementation, specifically the get System text method not working at all Due to that it requests a unicode clipboard format which doesn't exist in some applications like visual studio code.
Instead of fixing the problem in Windows, I added pyperclip which works great. I thought we could use it to overhaul the entire clipboard class. There are some things to consider first:
1. The current implementation supports storing many different clipboard formats inside its contents dictionary.Pyperclip only supports unicode text which would make formats and all related functions obsolete.
2.Pyperclip is a dependency and we may not want it.

With these limitations, is it worth It to get multi-platform support ?

**Comment by Versatilus** [comment]
It would be great if you could provide a sample file. I don't seem to be
having the same issue, but I also only have UTF-8/ASCII files.

**Comment by Danesprite** [comment]
I did mention pyperclip in issue #8, but yes, this would be nice if everything still works.

I'm not sure about other clipboard formats being made obsolete by using unicode though. Perhaps `Clipboard.get_system_text` could check the current format rather than assuming the content is unicode? [win32clipboard.IsClipboardFormatAvailable](http://timgolden.me.uk/pywin32-docs/win32clipboard__IsClipboardFormatAvailable_meth.html) seems to be the right function for doing that.

As to your other consideration, while pyperclip is an additional dependency, it doesn't require anything else to be installed on Windows or MacOS, only on Linux. Setuptools should just download and install it automatically because it's on PyPI [here](https://pypi.org/project/pyperclip/).

**Comment by gerrish** [comment]
I implied that get_system_text would use the pyperclip.copy method instead of fixing the current Windows only implementation.  I was thinking this Could be done for all the class methods. If we do this, formats are dealt with by pyperclip, so there's no point in the clipboard class containing things like the Dictionary with content mapped to format. Furthermore, if pyperclip doesn't support a format neither can we and currently it only supports unicode text.

**Comment by Danesprite** [comment]
Alright then, I'll add a feature branch on this with some unit tests. I'd also be happy to review pull requests on issues like this.

I agree with @Versatilus, if you're copy/pasting non-ASCII text, that might make a difference in some way.

**Comment by gerrish** [comment]
It was actually python 2.7 code so I doubt there was anything non-ascii in the file. It was one of caster's files.
I will try to contribute something in the next days.

**Comment by Danesprite** [comment]
Ah okay, thanks for clarifying that.

I have some work done on this already. I've tried to keep the changes backwards-compatible with the format->contents dictionary approach. I'll put it up soon.

**Comment by Danesprite** [comment]
The changes are in the feat/multi-platform-clipboard branch. I've run the new tests on Windows 10 and on my Linux machine with success. Let me know if it works for you.

Are there applications which work with the Windows-only implementation and not with `pyperclip`? I'm a little uneasy about removing support for the other clipboard formats altogether.

I was thinking that having the `Clipboard` class in the `dragonfly.windows` sub-package doesn't make much sense after these changes. Maybe a different package like `dragonfly.util` or `dragonfly.system` could be used for multi-platform functionality like this. The current `clipboard` module could then import from that package for backwards-compatibility.

Just going to note here that the `documentation/clipboard.txt` file needs updating.
