### ISSUE TITLE
Mappings get executed when the grammar does not match

### ISSUE THREAD

**Issue by dylan-chong** [Danesprite/dragonfly#37]
https://github.com/t4ngo/dragonfly/issues/71

**Comment by Danesprite** [comment]
I'll have a look into this soon. It could be a problem in one of dragonfly's decode methods related to rule references if `exported=False` didn't fix it for you.

**Comment by dylan-chong** [comment]
Hey just wondering if you managed to get a chance to look at this bug. If you've been busy, that's okay i can manage @Danesprite

**Comment by dylan-chong** [comment]
Ah,  I mustn't have tested this properly previously, as using the fix that @t4ngo suggested seems to fix the problem. Sorry for wasting time :(

**Comment by Danesprite** [comment]
@dylan-chong No problem. I'll close the issue now.
