### ISSUE TITLE
Backwards incompatible change to Text action is missing from changelog

### ISSUE THREAD

**Issue by caspark** [Danesprite/dragonfly#51]
In 0.10, the Text action seems to have been changed (in pull request #44 by @versatilus ?) so that it no longer respects modifier keys being held down.

Although this is a backwards incompatible change, it seems worthwhile for easier typing of Unicode characters, especially since the original dragonfly documentation says

> It differs from the Key action in that Text is used for typing literal text, while dragonfly.actions.action_key.Key emulates pressing keys on the keyboard.

which implies that Text and Key do not work the same.

However it would be a good idea to document this backwards incompatible change in the change log, especially for the benefit of people moving over from original dragonfly (e.g. if I remember rightly, the original multiedit grammar relies on holding down modifier keys to modify Text actions). It might also be helpful to especially call this out in the documentation for the Text action too.

cc @wolfmanstout - my grammar was originally based on [your repeat grammar](https://github.com/wolfmanstout/dragonfly-commands/blob/master/_repeat.py), so I suspect you will run into this too (your `full_key_action_map` will contain Text actions which won't work with `combo_key_element`'s pressing of modifier keys).

**Comment by Danesprite** [comment]
Thanks for noticing this. I'll update the changelog and documentation for `Text` to reflect the changes. 

To get the previous behaviour, `unicode_keyboard` can be set to false in `~/.dragonfly2-speech/settings.cfg` or `use_hardware` can be set to `True` for individual `Text` actions:

```Python
Text("test", use_hardware=True)

```

I'm wondering whether an [additional] `use_unicode` parameter would make more sense. What do you think @Versatilus?

**Comment by Danesprite** [comment]
On second thoughts, an additional parameter seems unnecessarily complicated. Documenting the `use_hardware` parameter as I have done should be fine.

**Comment by wolfmanstout** [comment]
Thanks Caspar for bringing this to my attention! The reason why I use Text to send keystrokes in combination with control characters is simply that I don't want to have to remember the arbitrary list of typeable names:
https://github.com/Danesprite/dragonfly/blob/master/dragonfly/actions/typeables.py

It doesn't make sense to me to have alternative names for keypresses which have an obvious printable representation (e.g. why not support Key(";") in addition to Key("semicolon")). Looks like it'd be easy to add these as alternative names without breaking the existing naming, shall we just do that?

I have some other comments on this change; I've added those to the pull request so I can comment on the code and avoid hijacking this issue: 
https://github.com/Danesprite/dragonfly/pull/44/files

**Comment by Danesprite** [comment]
Adding aliases for typeables sounds good to me. If I'm not mistaken, ':', '/', '-' and ',' would need to be excluded from that because they are used for modifiers, keypress delays and character repetitions in `Key`.

Thanks for the comments. I'll see what I can do to help out there.

**Comment by Versatilus** [comment]
After reading this, I think the correct solution is to hot fix this code to be disabled by default. People should be a able to opt in for the time being.

Part of the rationale for these functionality changes can be read in the newest comments added to the pull request at https://github.com/Danesprite/dragonfly/pull/44#discussion_r245466740.

**Comment by Danesprite** [comment]
@caspark version 0.10.1 should resolve this issue. You just need to modify/delete the *~/.dragonfly2-speech/settings.cfg* file. I've mentioned that in the changelog and added a section to [Text's documentation](https://dragonfly2.readthedocs.io/en/latest/actions.html#windows-unicode-keyboard-support).

**Comment by caspark** [comment]
Got it. Thanks for everyone's quick work to resolve this!
