### ISSUE TITLE
Dragonfly monitor returns rectangle of wrong dimensions if windows dpi scaling is enabled

### ISSUE THREAD

**Issue by gerrish** [Danesprite/dragonfly#7]
This is a bug originally detected in Caster development. Windows has a dpi scaling option which is mandatory for higher resolutions to make text readable. When this is set to anything but 100%, dragonfly monitor returns a smaller rectangle than the actual screen size. The rectangle's area and dimensions are exactly divided by the dpi scaling. Thus, the function which is used inside dragonfly is probably returning the actual rendering resolution and not the end result which is upscaled.This is very problematic for multiple monitors especially Which can each have different dpi scaling values because you can know neither their real resolution nor their actual positions on the virtual desktop.

 Furthermore, I was told (didn't have much time to look at the code) that dragonfly actually calculates the monitors variable only on startup. This is also problematic because the scaling value can change at any time and the correct dimensions should be returned Every Time.

Suggestions to fix this

1. Use the EnumDisplayMonitors function to get information about the monitors since it returns the Proper values.
2. Make the rectangle attributes into properties or functions which will be dynamically calculated on runtime.
I Could try my hand to fix this But I'm not very Familiar with the cpython API.

**Comment by Danesprite** [comment]
`EnumDisplayMonitors` is used to get the values already. Getting the monitor attributes every time sounds like a good way to fix this issue, as they are indeed only calculated at startup. I'll have a look into this tomorrow for you. I'm unable to test with multiple monitors in my Windows VM at the moment unfortunately.

According to `git blame`, most of `monitor.py` hasn't been updated since 2008, so maybe scaling wasn't so important back then.

**Comment by gerrish** [comment]
I meant the function from win32api which returns proper results compared to the current implementation. I'm not sure if it is enough to calculate every time without this fix because as I said it also reports wrong values. Even with startup calculation, it should always return the dimensions of the screen when dragon was started which it doesn't.

**Comment by gerrish** [comment]
If it doesn't hurt performance, which I doubt it will, it would be best if the monitor variable is rebuilt when needed since it will be annoying to reboot dragon every time something changes. This includes getting the rectangles.
Alternatively, keep it on startup but add a method to refresh the variable so that in sensitive applications like Mouse grids we can explicitly ask for the latest settings.

**Comment by LexiconCode** [comment]
Should we consider implementation for Linux and Mac OS as well? Since Windows relies on `win32api.EnumDisplayMonitors`?

**Comment by Danesprite** [comment]
I think `EnumDisplayMonitors` could just be called every time, it returns fairly quickly. Maybe the `Rectangle` objects for monitors could be reinitialised instead, so you don't end up using invalid ones. I'll make some changes shortly and do some testing.

@LexiconCode I had the same thought. Either the `xrandr` command or [python-xlib](https://github.com/python-xlib/python-xlib) could be used for Linux. I don't know about macOS though.

**Comment by Danesprite** [comment]
Let me know if that fixes it for you. I've done some testing on Windows 10 and it seems to be working.

**Comment by gerrish** [comment]
Works great on my computer as well (Windows 10 125 % scaling).

**Comment by Danesprite** [comment]
So I'll close this for now, can always reopen it if I've broken something else with those changes.

**Comment by LexiconCode** [comment]
@Danesprite now that Dragonfly is cross-platform is this something that we need to address in Mac and Linux?

**Comment by Danesprite** [comment]
It doesn't look like this is a problem on X11 because the monitor list is already updated. It would be an issue on macOS because I don't know how to get updated monitor information using `pyobjc`. You need to restart the interpreter after changing the monitor configuration on macOS.

**Comment by LexiconCode** [comment]
This looks like a useful commitment of the project implementing DPI awareness https://github.com/yinkaisheng/Python-UIAutomation-for-Windows/commit/2e7ced934fb953a6deed21e682a4dce612ee8e2f

**Comment by Danesprite** [comment]
Hmm. Thanks for this. What they have done is quite clever. Remembering back to PR #305, neither @wolfmanstout nor myself could figure out how to actually use the [`SetThreadDpiAwarenessContext()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setthreaddpiawarenesscontext) function from Python. Microsoft's documentation seemed to suggest it could only be used from C++, but clearly that is not the case.
